sudo: required
services:
  - docker
language: python
python:
  - "3.9"
install:
  - pip install -e .
  - pip install flake8
  - pip install isort
before_script:
  - isort meeting_scheduler -c
  - flake8 meeting_scheduler
script:
  - pytest
