language: python
python:
  - "3.9"

install:
  - pip install .
  - pip install -r requirements.txt
  - pip install flake8
  - pip install isort
before_script:
  - isort meeting_scheduler -c -v
  - flake8 --ignore E402,F401 meeting_scheduler
script:
  - pytest
