version: "3"

volumes:
  postgres_volume:

services:
  api_service:
    build: .
    container_name: rest_service
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
        - 49154:5000
    depends_on:
        - postgres_db
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    volumes:
        - postgres_volume:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=test
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=postgres
    restart: always
